version: '3'

services:

  portainer:
    image: portainer/portainer:1.24.1
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Data/Apps/Portainer:/data
